#.travis.yml
sudo: required

dist: trusty

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

language: node_js

node_js:
  - 6.10.2

branches:
  only:
    - master

before_script:
  - set -e
  - npm install

script:
  - npm run-script build