#.travis.yml
sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

language: node_js
node_js:
  - 6.10.2
before_script:
  - set -e
  - chmod a+x ./deploy.sh
  - npm install
script:
  - npm run-script build
  - cp ./Dockerfile ./dist/
deploy:
  - provider: script
    script: ./deploy.sh $TRAVIS_TAG $DOCKER_USERNAME $DOCKER_PASSWORD
    skip_cleanup: true
    on:
      tags: true