apiVersion: v1
kind: Service
metadata:
  labels:
    app: shop-ui
    env: dev
    ver: v1
  name: 'shop-ui'
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: shop-ui